### ISSUE TITLE
Win 10 x64 errors

### ISSUE THREAD

**Issue by MadProf123** [dmedlinger/CanaData#1]
There are character encoding issues I have run into when running on a Win 10 x64.
The program either stops at that point (giving truncated output) or completely quits.

**Comment by dmedlinger** [comment]
Thanks for bringing this up!

I've created a new branch and updated it with a version that will hopefully account for this issue.

Please download and try it here: https://github.com/dmedlinger/CanaData/tree/Windows-Encoding-Issues

Let me know how that goes and if it works I'll merge those changes into the main branch.

**Comment by dmedlinger** [comment]
This should be resolved! Please see the newest version just pushed.
